spring:
  rabbitmq:
    host: 10.159.0.101
    port: 5672
    username: root
    password: 123456
    publisher-confirm-type: correlated #开启发布确认，发布消息成功到交换器后会触发回调方法
    template:
      mandatory: true #回退消息
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
